name: murphyz
favicon: null
layout_spectrum: 0.17984864301979542
typography_spectrum: 0.2480130661278963
title: murphyz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424443'
    - '#68696d'
    - '#a09694'
    - '#b6b8b7'
    - '#d1d5d6'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.6102512187790126
purpose: []
